// Event.preventDefault();    This command is supposted to help with not sending the user to the top of the page whenever they click a link, but i cant get it to work. Placement?

// Scenario: click a button to fade away former content within a div, and fade in the content associated with the button you clicked.

// For this to work, you need to add a data-rel to the html of each <a> that is clicked. The data-rel is the id of the article associated with that button.


// wrap all in document ready function
$(document).ready(function(){
  console.log("JavaScript loaded, Huzzah!")
  $(".article2345").hide();
  $(".photo2345").hide();

  $('#sidebar-content a').click (function(evt) {
    console.log("Click")

    // article fade in/fade out section
    $(".allSeasonalArticles").fadeOut (100);
    // Wrapps "this", does not wrap the resulting string. example "#article1" is just a string, not an actual id.
    var articleId = $(this).data("rel")
    // test print out "var articleId = #article1" to prove that when you click the button, a string of the associated article ID is generated by the variable "articleId"
    console.log("click <a> button and var articleID generates a string = "+ articleId)
    // wraps the result of the variable "articleId"
    var article = $(articleId)
    // test print the variable "article" attribute id
    console.log("anything="+ article.attr('id'))
    // test print the variable "article"
    console.log("anything3="+ article.toString())
    //this is asking the same as the line above
    console.log("anything4="+ article)
    article.fadeIn (1200);

    // photo fade in/fade out section
    $(".allphotos").fadeOut (0);
    var photoId = $(this).attr('id')
    var photo = $(photoId)
    photo.fadeIn (1200);
  });

});
